spring:
  profiles:
    active:
      - inMemoryDB
graphql:
  servlet:
    corsEnabled: true
    enabled: true
physicalImageLocation: /temp/
imageServer: http://localhost:8080/images/
---
spring:
  profiles: inMemoryDB
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=- 1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: